# Generated by Django 4.2 on 2024-12-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(max_length=1000)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bilder', models.ImageField(upload_to='produkt_bilder/')),
                ('produkt_pdf', models.FileField(blank=True, null=True, upload_to='produkt_pdfs/')),
                ('produkt_typ', models.CharField(choices=[('elektronik', 'Elektronik'), ('bekleidung', 'Bekleidung'), ('moebel', 'Möbel'), ('buecher', 'Bücher'), ('schmuck', 'Schmuck'), ('kosmetik', 'Kosmetik'), ('sport', 'Sportartikel'), ('lebensmittel', 'Lebensmittel'), ('spielzeug', 'Spielzeug'), ('haushalt', 'Haushaltswaren'), ('geschenke', 'Geschenke'), ('gesundheit', 'Gesundheitsprodukte'), ('musik', 'Musikinstrumente'), ('kunst', 'Kunst und Dekoration'), ('software', 'Computersoftware'), ('werkzeuge', 'Werkzeuge')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkts', related_query_name='produkt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkts',
                'ordering': ['name'],
            },
        ),
    ]
