# Generated by Django 4.2 on 2024-12-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='bilder',
        ),
        migrations.CreateModel(
            name='ProduktBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='produkt_bilder/')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktbilder', to='Onlineshop.produkt')),
            ],
        ),
    ]
