# Generated by Django 4.2 on 2024-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Onlineshop", "0005_produkt_produkt_bild_delete_produktbild"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["timestamp"],
            },
        ),
    ]
