# Generated by Django 4.2 on 2024-12-17 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Onlineshop", "0007_comment_myuser_comment_produkt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="myuser",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="produkt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produkt_created_by",
                related_query_name="produkt_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
