# Generated by Django 4.2 on 2025-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onlineshop', '0007_vote_user_melden_comment_melden_user_comment_produkt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenutzerProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('userlastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('some_file', models.FileField(blank=True, null=True, upload_to='some_files/')),
            ],
        ),
    ]
