# Generated by Django 4.2 on 2024-12-27 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Onlineshop", "0008_rename_myuser_comment_user_alter_produkt_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bewertung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sterne", models.IntegerField()),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "produkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Onlineshop.produkt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("produkt", "user")},
            },
        ),
    ]
