# Generated by Django 4.2 on 2024-12-30 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Onlineshop", "0012_melden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="melden",
            old_name="bewmelden",
            new_name="melden",
        ),
    ]
