# Generated by Django 4.2 on 2025-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Onlineshop", "0013_rename_bewmelden_melden_melden"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkt",
            name="sterne",
            field=models.IntegerField(default=0),
        ),
    ]
