# Generated by Django 4.2 on 2025-01-11 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Onlineshop", "0014_produkt_sterne"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produkt",
            name="sterne",
        ),
    ]
