# Generated by Django 4.2 on 2025-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Onlineshop", "0016_benutzerprofil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benutzerprofil",
            name="profil_image",
        ),
        migrations.AddField(
            model_name="benutzerprofil",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
