# Generated by Django 4.2 on 2025-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0003_alter_myuser_options_alter_myuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="myuser",
            name="gets_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="myuser",
            name="some_file",
            field=models.FileField(blank=True, null=True, upload_to="uploaded_files"),
        ),
        migrations.AddField(
            model_name="myuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("SU", "superuser"),
                    ("CS", "customer support"),
                    ("CU", "customer user"),
                    ("QA", "quality assurance"),
                ],
                default="CU",
                max_length=2,
            ),
        ),
    ]
