# Generated by Django 4.2 on 2025-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0004_alter_myuser_options_myuser_gets_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("SU", "superuser"),
                    ("CS", "customer support"),
                    ("CU", "customer user"),
                    ("QA", "quality assurance"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
    ]
