# Generated by Django 4.2 on 2025-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAdmin", "0005_alter_myuser_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="gets_discount",
        ),
        migrations.AddField(
            model_name="myuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("SU", "superuser"),
                    ("CS", "customer support"),
                    ("CU", "customer user"),
                ],
                default="CU",
                max_length=2,
            ),
        ),
    ]
